{% set version = "2.22.0" %}

package:
  name: libva
  version: {{ version }}

source:
  url: https://github.com/intel/libva/archive/{{ version }}.tar.gz
  fn: libva-{{ version }}.tar.gz
  sha256: 467c418c2640a178c6baad5be2e00d569842123763b80507721ab87eb7af8735

build:
  skip: true  # [osx]
  number: 1
  # Pretty good forward compatibility
  # https://abi-laboratory.pro/index.php?view=timeline&l=libva
  run_exports:
    - {{ pin_subpackage('libva', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - meson
    - ninja
  host:
    - libdrm           # [linux]
    - libgl-devel      # [linux]
    - libglx-devel     # [linux]
    - libegl-devel     # [linux]
    - wayland          # [linux]
    - libxcb           # [linux]
    - xorg-libx11      # [linux]
    - xorg-libxext     # [linux]
    - xorg-libxfixes   # [linux]
  run:
    - wayland-protocols  # [linux]
    - xorg-libxfixes     # [linux]

test:
  commands:
    - test -f $PREFIX/include/va/va.h                    # [unix]
    - test -f $PREFIX/lib/libva.so                       # [unix]
    - test -f $PREFIX/lib/libva.so.2                     # [unix]
    - test -f $PREFIX/lib/pkgconfig/libva.pc             # [unix]
    - test -f $PREFIX/include/va/va_drm.h                # [unix]
    - test -f $PREFIX/lib/libva-drm.so                   # [unix]
    - test -f $PREFIX/lib/libva-drm.so.2                 # [unix]
    - test -f $PREFIX/lib/pkgconfig/libva-drm.pc         # [unix]
    - test -f $PREFIX/include/va/va_glx.h                # [unix]
    - test -f $PREFIX/lib/libva-glx.so                   # [unix]
    - test -f $PREFIX/lib/libva-glx.so.2                 # [unix]
    - test -f $PREFIX/lib/pkgconfig/libva-glx.pc         # [unix]
    - test -f $PREFIX/include/va/va_wayland.h            # [unix]
    - test -f $PREFIX/lib/libva-wayland.so               # [unix]
    - test -f $PREFIX/lib/libva-wayland.so.2             # [unix]
    - test -f $PREFIX/lib/pkgconfig/libva-wayland.pc     # [unix]
    - test -f $PREFIX/include/va/va_x11.h                # [unix]
    - test -f $PREFIX/lib/libva-x11.so                   # [unix]
    - test -f $PREFIX/lib/libva-x11.so.2                 # [unix]
    - test -f $PREFIX/lib/pkgconfig/libva-x11.pc         # [unix]
    - if not exist %PREFIX%/Library/bin/va.dll exit 1       # [win]
    - if not exist %PREFIX%/Library/lib/va.lib exit 1       # [win]
    - if not exist %PREFIX%/Library/include/va/va.h exit 1  # [win]

about:
  home: https://github.com/intel/libva
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Libva is an implementation for VA-API (Video Acceleration API)

  # The remaining entries in this section are optional, but recommended
  description: |
    VA-API is an open-source library and API specification, which provides
    access to graphics hardware acceleration capabilities for video processing.
    It consists of a main library and driver-specific acceleration backends
    for each supported hardware vendor.

extra:
  recipe-maintainers:
    - gabm
    - hmaarrfk
    - ehfd
